Shop Hooking!
xHyroM/spawnergenz pull request #2
Opened 2023-07-17 10:21 UTC by Saturn745

This PR introduces hooking into different shop plugins for selling the loot in spawners

- [ ] Essentials
- [ ] EconomyShopGUI (Tested with the Premium version. Free version has not been tested but should work fine) 
- [ ] PeddlersPocket (Waiting for a API method to get the sell amount for an item)

2023-07-17 14:55 UTC, xHyroM requested changes

2023-07-17 14:55 UTC, xhyrom commented on src/main/java/me/xhyrom/spawnergenz/SpawnerGenz.java
> +        Class<? extends ShopHook> pluginClass = shopPlugins.get(this.getConfig().getString("shop-plugin"));
We can use `switch` statement instead of using array and then putting values into it.

2023-07-17 14:56 UTC, xHyroM requested changes

2023-07-17 14:56 UTC, xHyroM commented on src/main/java/me/xhyrom/spawnergenz/SpawnerGenz.java
> +        if (!setupVault()) {
We can move this things into hooks/Hooks instead of flooding main class with this stuff.

2023-07-17 15:42 UTC, xHyroM commented
You can update Peddler's Pocket to version 1.1.0 for new api methods!

2023-07-17 17:04 UTC, Saturn745 commented on src/main/java/me/xhyrom/spawnergenz/SpawnerGenz.java
> +        Class<? extends ShopHook> pluginClass = shopPlugins.get(this.getConfig().getString("shop-plugin"));
I considered that as well but ended up going with this route. I will switch it to a switch statement

2023-07-19 13:00 UTC, xhyrom commented on src/main/resources/config.yml
> +# Available shop plugins: Essentials, EconomyShopGUI(-Premium), PeddlersPocket(TODO)
you can remove (TODO) here

2023-07-19 13:01 UTC, xHyroM commented on src/main/java/me/xhyrom/spawnergenz/SpawnerGenz.java
> +        new Hooks();
just preference, dont we want to have `Hooks#init` static than creating class? That's just preference but there's no reason  for not using static functions

2023-07-19 13:01 UTC, xHyroM commented on src/main/java/me/xhyrom/spawnergenz/SpawnerGenz.java
> +        new Hooks();
tell your opinion

2023-07-19 20:33 UTC, merged